Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20111021-1
extra : transplant_source : %B4%C1hN%11%BE%40%C1%3A%08%D2Q%A8uO_%3C%C2G%06