Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20111015-4-hg-git
extra : transplant_source : u%7E%5D%1F%99%C5%AE%B6f%7E3%8F%F9%99%01%98%08%F3%E4%8C